site_name: Cloud Native LinuxONE Workshop
repo_url: https://github.com/ibm-wsc/cloud-native-linuxone/
site_url: https://ibm-wsc.github.io/cloud-native-linuxone/
edit_uri: edit/main/docs
nav:
    - 1. Home: index.md
    - 2. Introduction: introduction.md
    - 3. Prerequisites: prerequisites.md
    - Build and Deploy Pet Clinic:
      - 4. Build and Deploy Overview: build-and-deploy/build_overview.md
      - 5. PetClinic Up and Running: build-and-deploy/upandrunning.md
    - Configure PetClinic's Pipeline:
      - 6. Configure Pipeline Overview: full-dev-pipeline/configure_overview.md
      - 7. Configure Build and Test: full-dev-pipeline/pipeline.md
      - 8. Configure Development Deployment: full-dev-pipeline/runpipeline.md
    - Test and Promote Pet Clinic:
      - 9. Test and Promote Overview: application-promotion/promote_overview.md
      - 10. Promoting Application: application-promotion/promote.md
      - 11. Integrating Git: application-promotion/git.md
      - 12. CI/CD in Action: application-promotion/action.md
    - Cleanup:
      - 13. Environment Cleanup: cleanup/full-cleanup.md
    - 14. Other resources: resources.md
    - 15. Propose a change: proposechange.md

theme: 
  name: material
  palette:
    scheme: preference
  favicon: images/pipelines-logo.png
  logo: images/pipelines-logo.png
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ibm-wsc
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/s390x
google_analytics:
  - UA-174658170-3
  - auto
markdown_extensions:
  - abbr
  - admonition
  - codehilite
  - footnotes
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde
  - attr_list
  - toc:
      permalink: true
plugins:
  - search
  - enumerate-headings:
      toc_depth: 6
      strict: true
  - print-site:
      add_to_navigation: true
