site_name: Cloud Native LinuxONE Workshop
repo_url: https://github.com/ibm-wsc/cloud-native-linuxone/
site_url: https://ibm-wsc.github.io/cloud-native-linuxone/
edit_uri: edit/main/docs
nav:
  - Home: index.md
  - Introduction: introduction.md
  - Cloud Lab:
    -  Prerequisites: cloud-lab/prerequisites.md
    -  Build and Deploy Pet Clinic:
        - cloud-lab/build-and-deploy/index.md
        - PetClinic Up and Running: cloud-lab/build-and-deploy/upandrunning.md
    - Configure PetClinic's Pipeline:
        - cloud-lab/full-dev-pipeline/index.md
        - Configure Build and Test: cloud-lab/full-dev-pipeline/pipeline.md
        - Configure Development Deployment: cloud-lab/full-dev-pipeline/runpipeline.md
    - Test and Promote Pet Clinic:
        - cloud-lab/application-promotion/index.md
        - Promoting Application: cloud-lab/application-promotion/promote.md
        - Integrating Git: cloud-lab/application-promotion/git.md
        - CI/CD in Action: cloud-lab/application-promotion/action.md
    - Add the "Sec" in "DevSecOps": cloud-lab/devsecops/devsecops.md
    - Cleanup: cloud-lab/cleanup/full-cleanup.md
    - REFERENCE 1. Setting up SonarQube Server in OpenShift: cloud-lab/devsecops/sonarqube.md
    - REFERENCE 2. Setting up PetClinic OpenShift Pipeline using yaml files: cloud-lab/yamlsetup.md
  - On-premises Lab:
    -  Build and Deploy Pet Clinic:
        - on-premises-lab/build-and-deploy/index.md
        - PetClinic Up and Running: on-premises-lab/build-and-deploy/upandrunning.md
    - Configure PetClinic's Pipeline:
        - on-premises-lab/full-dev-pipeline/index.md
        - Configure Build and Test: on-premises-lab/full-dev-pipeline/pipeline.md
        - Configure Development Deployment: on-premises-lab/full-dev-pipeline/runpipeline.md
    - Test and Promote Pet Clinic:
        - on-premises-lab/application-promotion/index.md
        - Promoting Application: on-premises-lab/application-promotion/promote.md
        - Integrating Git: on-premises-lab/application-promotion/git.md
        - CI/CD in Action: on-premises-lab/application-promotion/action.md
    - Add the "Sec" in "DevSecOps": on-premises-lab/devsecops/devsecops.md
  - Lab Logistics: logistics.md 
  - Other resources: resources.md
  - Propose a change: proposechange.md

theme:
  name: material
  favicon: images/pipelines-logo.png
  logo: images/pipelines-logo.png
  features:
    - content.code.copy
    - navigation.indexes
    - navigation.tracking
    - content.action.edit
    - content.action.view
    - navigation.footer
    - content.tabs.link
    - search.share
  palette:
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: black
      accent: red
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: black
      accent: red
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

copyright: >
  Copyright &copy; 2022 IBM –
  <a href="#__consent">Change cookie settings</a>

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ibm-wsc
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/s390x
  analytics:
    provider: google
    property: UA-174658170-3
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/heart
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/heart-broken
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help me improve this page by
            using my <a href="https://github.com/ibm-wsc/cloud-native-linuxone/issues/new/?title=[Feedback]+{title}+-+{url}" target="_blank" rel="noopener">feedback form</a>.
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make the documentation as good as possible.

markdown_extensions:
  - abbr
  - admonition
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.highlight
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/glossary.md
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tilde
  - attr_list
  - toc:
      permalink: true
plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
  - print-site:
      add_to_navigation: true
