site_name: Cloud Native LinuxONE Workshop
repo_url: https://github.com/ibm-wsc/cloud-native-linuxone
edit_uri: edit/main/docs
nav:
    - Home: index.md
    - Introduction: introduction.md
    - Prerequisites: prerequisites.md
    - Build and Deploy Pet Clinic:
      - Section Overview: build-and-deploy/overview.md
      - PetClinic Up and Running: build-and-deploy/upandrunning.md
    - Configure PetClinic's Pipeline:
      - Section Overview: full-dev-pipeline/overview.md
      - Configure Build and Test: full-dev-pipeline/pipeline.md
      - Configure Development Deployment: full-dev-pipeline/runpipeline.md
    - Test and Promote Pet Clinic:
      - Section Overview: application-promotion/overview.md
      - Promoting Application: application-promotion/promote.md
      - Integrating Git: application-promotion/git.md
      - CI/CD in Action: application-promotion/action.md
    - Glossary of terms: glossary.md
    - Other resources: resources.md
    - Propose a change: proposechange.md

theme: 
  name: material
  palette:
    scheme: preference
  favicon: images/pipelines-logo.png
  logo: images/pipelines-logo.png
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ibm-wsc
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/s390x
google_analytics:
  - UA-174658170-3
  - auto
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde
  - attr_list
  - toc:
      permalink: true
